# Generated by Django 4.0.4 on 2022-05-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPenName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('awards', models.CharField(max_length=100)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
            ],
        ),
    ]
